name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Create tar archive
        run: |
          tar -czf build.tar.gz dist  # Create the tar archive

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build.tar.gz"
          target: "/home/${{ secrets.EC2_USER }}/build.tar.gz"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Unpacking and deploying..."
            tar -xzf /home/${{ secrets.EC2_USER }}/build.tar.gz/build.tar.gz -C /var/www/html/React_Project
            sudo rm -rf /home/${{ secrets.EC2_USER }}/build.tar.gz
            sudo systemctl restart apache2
            echo "Deployment completed!"
