name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # 🟢 NEW: Create tar archive (instead of zipping)
      - name: Create tar archive
        run: |
          tar -czf build.tar.gz dist  # Create the tar archive

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build.tar.gz"  # Source is now tar file instead of zip
          target: "/home/${{ secrets.EC2_USER }}/build.tar.gz"  # Transfer tar file to EC2

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Unpacking and deploying..."
            tar -xzf /home/${{ secrets.EC2_USER }}/build.tar.gz -C /var/www/html/React_Project  # Unpack tar file
            sudo rm /home/${{ secrets.EC2_USER }}/build.tar.gz  # Remove tar file after deployment
            sudo systemctl restart apache2  # Restart apache server
            echo "Deployment completed!"



# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "20"

#       - name: Install dependencies
#         run: npm install

#       - name: Build React app
#         run: npm run build

#         # 🟢 NEW: Verify zip is installed properly
#       - name: Install zip utility
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y zip
#           zip -v  # ✅ Confirm zip is now available

#       # ✅ Compress the correct folder — double check that 'dist' exists
#       - name: Compress build folder
#         run: |
#           ls -la dist  # ✅ Optional: Confirm build folder exists
#           zip -r build.zip dist

#       # - name: Install zip utility
#       #   run: sudo apt-get update && sudo apt-get install -y zip

#       # - name: Compress build folder
#       #   run: zip -r build.zip dist

#       - name: Copy build to EC2
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_KEY }}
#           source: "build.zip"
#           target: "/home/${{ secrets.EC2_USER }}/build.zip"

#       - name: Deploy on EC2
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_KEY }}
#           script: |
#             echo "Unzipping and deploying..."
#             sudo rm -rf /var/www/html/React_Project/dist
#             unzip /home/${{ secrets.EC2_USER }}/build.zip -d /var/www/html/React_Project  
#             sudo rm /home/${{ secrets.EC2_USER }}/build.zip
#             sudo systemctl restart apache2
#             echo "Deployment completed!"


